name: Build and test.

on:
  push:
    paths:
      - Brer/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./Brer  

      - name: Test
        run: dotnet test --verbosity normal
        working-directory: ./Brer
