name: Auto Publish to NuGet

on:
  push:
    paths:
      - Brer/**
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
          

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./Brer  # moving working-directory here

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./Brer

      - name: Test
        run: dotnet test --verbosity normal
        working-directory: ./Brer

      - name: Pack
        run: dotnet pack --no-build -c Release -o out
        working-directory: ./Brer

      - name: Push NuGet Package
        run: dotnet nuget push out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        working-directory: ./Brer 
